# Welcome to Jekyll!
#

# Site settings
title: ConcaveTeam
description: |
  Autonomous Nerf Launcher
owner: ConcaveTeam
first_published: 2018 # if migrating another site, the year of your first publish
email: concavemail@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "concaveteam.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/concaveteam
  email: mailto:concavemail@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
sass:
 style: compressed
